### ISSUE TITLE
NullPointerException ResourceHandlerImpl.java:299 on WildFly15

### ISSUE THREAD

**Issue by hansprueller** [albfernandez/richfaces#26]
I was running a very "dynamic" JSF view with a lot of ajax-Updates and RichFaces Drag-and-Drop functions with RichFaces 4.5.16.Final and WildFly10, with basically no major problems.

After upgrading to WildFly 15, I get a NullPointer Exception when the page is loaded (see full stacktrace below). Seems the problem occurs due to some library upgrades (JSF, Servlet spec, undertow, whatever) in WildFly:

NullPointerException at ResourceHandlerImpl.java:299

The problem is, that all ajax-based page updates are not working any more on this page. 

I would try to fix this NullPointerException in RichFaces ResourceHandlerImpl.java like this:

` public String getRendererTypeForResourceName(String resourceName) {

    	//NPE fix:
        if ((resourceName!=null) && (resourceName.endsWith(".ecss"))) {
            return "javax.faces.resource.Stylesheet";
        }
        //NPE fix:
        if ((resourceName!=null) &&(resourceName.endsWith(ResourceLibraryRenderer.RESOURCE_LIBRARY_EXTENSION))) {
            return ResourceLibraryRenderer.RENDERER_TYPE;
        }

        return defaultHandler.getRendererTypeForResourceName(resourceName);
    }`

and hope it works again after that.  But I do not want to create my own fork, probably others could need this fix too.

Any chance you integrate this NPE fix into your git repo and release new jars?

regards,
HANS

=
`16:17:12,629 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-4) Error Rendering View[/faces/srv/teamplanning.xhtml]: java.lang.NullPointerException
	at org.richfaces.resource.ResourceHandlerImpl.getRendererTypeForResourceName(ResourceHandlerImpl.java:299)
	at javax.faces.application.ResourceHandlerWrapper.getRendererTypeForResourceName(ResourceHandlerWrapper.java:218)
	at com.sun.faces.context.PartialViewContextImpl.renderComponentResources(PartialViewContextImpl.java:506)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:338)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at org.richfaces.context.ExtendedPartialViewContext.processPartial(ExtendedPartialViewContext.java:264)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1124)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:465)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:81)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at com.lbslogics.ims.servlet.filter.XssFilter.doFilter(XssFilter.java:78)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at jodd.servlet.filter.GzipFilter.doFilter(GzipFilter.java:70)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by wlhUser** [comment]
Hello Hans,

I'm also planning to use RF 4.5.16 with Wildfly15, but currently I have problems even running it on Wildfly10, in combination with Primefaces 6.2.
As is see from your stack trace, that you are using Primefaces as well, may I ask which version you are using. In case you are using PF 6.2 or higher, do you also experience that the content of the 'oncomplete' methods of the a4j elements is not being re-rendered correctly after executing an element.
=> https://github.com/albfernandez/richfaces/issues/25

Best Regards
Holger

**Comment by hansprueller** [comment]
Hello Holger,

I have been using RF 4.5.16 with WildFly 10 in combination with PrimeFaces 6.0 with basically only isolated problems (mainly caused because of different jquery versions and incompatibilities on pages where RF and PF components are mixed).

So I can't tell that there are any major issues with RF 4.5 and PF 6.0 on WildFly 10. On WildFly 15 I am also testing the upgrade to PF 6.2 but I got stuck because of the NullPointerException Problem in RichFaces 4.5 ... 

I hope we can solve this somehow...

**Comment by wlhUser** [comment]
Hello Hans,

thanks for your answer.  The problem I'm experiencing starts occurring with the usage of PF6.2, but I suppose I will soon run also in the NPE reported by you.

Regards

Holger

**Comment by albfernandez** [comment]
I've commited your patch! Thanks!
I'll try to make a release this weekend.

We have been using Richfaces 4.5.23 + Primefaces 6.1 in the same server / app. It works pretty well while you don't mix both of them in the same page (can be done with some components, but with care).
We're now finishing the full migration to Primefaces

**Comment by albfernandez** [comment]
There are two branch in this project
master -> 4.6 -> JQuery 3
4.5.x -> 4.5 -> JQuery 1

I'll release both

**Comment by wlhUser** [comment]
Hello Alberto,
thank you for providing the new releases.
As you wrote that you are about to finish the full migration to PrimeFaces, does this mean that you will abandon the maintenance of the current richfaces branches in the near future?

Regards

Holger

**Comment by hansprueller** [comment]
Hi @albfernandez !

Thanks for the Info. I will wait for the release (can up update us here on this ticket?)

Which branch would you suggest to use in combination with PrimeFaces? From my experience there are mainly jquery based problems when using RF and PF in parallel (because of different jquery versions I guess).

So for PrimeFaces 6.0  and PrimeFaces 6.2 , I guess we should use 4.6  ?? 

kind regards,
Hans

**Comment by albfernandez** [comment]
> As you wrote that you are about to finish the full migration to PrimeFaces, does this mean that you will abandon the maintenance of the current richfaces branches in the near future?

I will apply patch and pull request, and publish new releases, but cannot test in real envirnoment, and have no much time. Help is always welcome

**Comment by albfernandez** [comment]
The issue regarding compatibility with Primefaces.
Primefaces uses jquery 1 up to version, 6.1. 6.2 and higher uses jquery 3.
So you must use richfaces 4.5.x with Primefaces <= 6.1 and richfaces 4.6.x with Primefaces >= 6.2

I've not tested Richfaces 4.6.x in real applications (i've tested and fixed in the showcase only), so expect some minor bugs.

**Comment by albfernandez** [comment]
Released!

https://github.com/albfernandez/richfaces/releases

**Comment by hansprueller** [comment]
@albfernandez  perfect, thanks a lot!

I just tested the new 4.6.7 release with my project running in combination with PrimeFaces 6.2  on WildFly 15 and: NullPointerException is gone and partial page updates / ajax features are working again!

**Comment by Emkas** [comment]
This is not because of WildFly but rather because of JSF 2.3 (default on WildFly 15). One of the many problems with handling resources in RF, I must say. For example resource duplication in HTML, which can break the order of includes (like in JavaScript files).

So, this may be related to: #95.
